version: "3.8"

services:
  app:
    build:
      context: ./apps/perpus-laravel  # Points to the Laravel directory
      dockerfile: Dockerfile  # Uses the Dockerfile inside perpus-laravel
    container_name: perpus_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./apps/perpus-laravel:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    networks:
      - perpus_network

  db:
    image: mysql:5.7
    restart: always
    container_name: perpus_db
    environment:
      MYSQL_DATABASE: 'perpusku_gc'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - perpus_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  perpus_network:

volumes:
  mysql_data:
