version: "3.8"

services:
  app:
    build:
      context: ./apps/perpus-laravel  # Points to the Laravel directory
      dockerfile: Dockerfile  # Uses the Dockerfile inside perpus-laravel
    container_name: perpus_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./apps/perpus-laravel:/var/www/html
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
    networks:
      - perpus_network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'perpusku_gc'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - perpus_network

networks:
  perpus_network:

volumes:
  mysql_data:
