events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 443 ssl;

        ssl_certificate     /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        # Route to App
        location /app/ {
            proxy_pass http://app:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            rewrite ^/app(/.*)$ $1 break;
        }

        # Route to Jenkins
        location /jenkins/ {
            proxy_pass http://jenkins:8443/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            rewrite ^/jenkins(/.*)$ $1 break;
        }

        # Route to Grafana
        location /grafana/ {
            proxy_pass http://grafana:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            rewrite ^/grafana(/.*)$ $1 break;
        }
    }
}
