events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 443 ssl;

        ssl_certificate     /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        
        location = /app {
            return 302 /app/login;
        }
        # Route to App
        location /app/ {
            rewrite ^/app(/.*)$ $1 break;
            proxy_pass http://app:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect / /app/;
        }

        # Route to Jenkins
         location /jenkins/ {
            rewrite ^/jenkins(/.*)$ $1 break;
            proxy_pass https://jenkins:8443;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect / /jenkins/;
            proxy_ssl_verify off;
        }

        # Route to Grafana
        location /grafana/ {
            rewrite ^/grafana(/.*)$ $1 break;
            proxy_pass http://grafana:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect / /grafana/;
        }
    }
}
