groups:
  - name: container_down
    rules:
      - alert: "Container Advisor Down"
        expr: up{job="cadvisor"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.name }} is down"
          description: "The container {{ $labels.name }} has been down for more than 2 minutes."
      - alert: "Perpus App Down"
        expr: absent(container_last_seen{name="perpus_app"})
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.name }} is down"
          description: "The container {{ $labels.name }} has been down for more than 2 minutes."
      - alert: "Perpus DB Down"
        expr: absent(container_last_seen{name="perpus_app"})
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.name }} is down"
          description: "The container {{ $labels.name }} has been down for more than 2 minutes."
