pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'development', url: 'https://github.com/Raihanarfi12/jenkins-repo.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Unit Testing') {
            steps {
                // Run your test file (assumes test.py exists and uses unittest)
                sh '''
                . venv/bin/activate
                python3 tests.py
                '''
            }
        }
    }
}
