version: '3.8'
services:
  jenkins:
    image: jenkins-https
    ports:
      - "443:8443"
      - "50000:50000"
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --httpPort=-1
      --httpsPort=8443
      --httpsKeyStore=/var/jenkins_home/jenkins_keystore.jks
      --httpsKeyStorePassword=$KEYSTORE_PASSWORD
volumes:
  jenkins_home:

